### ISSUE TITLE
Block updates, doors and held item problems

### ISSUE THREAD

**Issue by comp500** [DragonetMC/Dragonet-Legacy#46]
Block updates aren't properly sent to and from the MCPE client.
When a block is placed on the PC minecraft client, it is shown, however destruction of blocks does not update until you place a block on the PC minecraft client. When you place a block on the MCPE client, it never shows up on the PC Minecraft client (and can be walked through on both). Block destruction, however, works from the MCPE client.

Doors also behave quite strangely, (oak doors, the other ones have no texture on MCPE), however this may be Glowstone's fault. When placed on PC, they show up on MCPE and open and close on PC (these changes showing up on PE), and no changes on MCPE show up on PC. Also, when one half is destroyed, the other stays intact.

Held items. PC > PE works, but PE > PC only shows one type of an item (e.g. only showing oak wood rather than spruce, for example). Also, players with the same name (eg comp500 on MCPE and PC) can occur, so they should be kicked.

Apart from a few glitches with the networking (as specified in the changelog), this system works, and is really great. I hope that you can keep developing Dragonet.

Testing devices: Dragonet 2.0.0pre-R4: iPod Touch 4 v0.11.1 alpha PE, MC 1.8.7 + Server running under Linux (ubuntu 14.04 if it even really makes any difference)

**Comment by DefinitlyEvil** [comment]
The networking became a bit more lager after switching to Glowstone++, I will look into this problem soon. But now I am busy on my work so I don't have much time doing this. Hopefully I will be free after 1-2 months.

**Comment by S0N-0F-A-S0N** [comment]
I've noticed all of these myself too, since even earlier versions.

On Tue, Jun 23, 2015 at 3:34 AM, The Evil Man notifications@github.com
wrote:

> The networking became a bit more lager after switching to Glowstone++, I
> will look into this problem soon. But now I am busy on my work so I don't
> have much time doing this. Hopefully I will be free after 1-2 months.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/46#issuecomment-114406543.

## 

This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

_Elijah Keane_
http://www.s0ncraft.com/_http://www.s0ncraft.com/_
http://www.s0ncraft.com/

**Comment by DefinitlyEvil** [comment]
@S0N-0F-A-S0N But it was bearable before, now it became worse.

**Comment by mastercoms** [comment]
Some door problems were fixed in this Glowkit update: https://github.com/GlowstonePlusPlus/Glowkit/commit/0facd12906843a2309c3fe0bfb6f5bc4fad63517, which Dragonet has yet to update to.

Could you describe the networking errors more? Realize that we're only in charge of PC to PC updates, and any errors you see PC to PE or vice versa are Dragonet's fault.

**Comment by mastercoms** [comment]
Doors have been completely fixed in this update: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/39a098f033301b3c5859467023ac58af9f26a4db

**Comment by DefinitlyEvil** [comment]
@mastercoms Will be merged soon. ;)

**Comment by comp500** [comment]
I've been testing on the test server. block updates PC > PE are pretty much the same as before, PE > PC nothing happens. Doors are pretty much fixed, apart from not being sent form PE > PC

**Comment by DefinitlyEvil** [comment]
@comp500 I will try to fix but I am now pretty busy. :(
